# Generated by Django 3.1.7 on 2021-06-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210603_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
