# Generated by Django 3.1.7 on 2021-07-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-correct', 'created'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Responses'},
        ),
    ]
