# Generated by Django 3.1.7 on 2021-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210706_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=0, max_length=100, unique=True, verbose_name='Identifier'),
        ),
    ]
