# Generated by Django 3.2.5 on 2021-07-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210720_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettingstarted',
            name='syllabus',
            field=models.TextField(blank=True, null=True, verbose_name='Syllabus'),
        ),
    ]
