# Generated by Django 3.2.5 on 2021-07-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_gettingstarted_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gettingstarted',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getting_started', to='courses.lesson'),
        ),
    ]
