# Generated by Django 3.2.5 on 2021-07-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_weeklycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycomment',
            name='week',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week'),
        ),
    ]
