# Generated by Django 3.2.5 on 2021-07-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210722_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercomments',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week'),
        ),
    ]
