# Generated by Django 3.2.5 on 2021-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('great_job', 'Great Job'), ('well_done', 'Well Done'), ('good_try', 'Good Try'), ('need_practice', 'Need More Practice')], max_length=50, null=True),
        ),
    ]
