# Generated by Django 3.2.5 on 2021-07-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_teachercomments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercomments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
