# Generated by Django 3.2.5 on 2021-07-27 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0019_alter_teachercomments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='score',
        ),
        migrations.CreateModel(
            name='ScoreStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
        ),
    ]
