# Generated by Django 3.2.5 on 2021-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210727_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettingstarted',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Syllabus'),
        ),
    ]
