# Generated by Django 3.2.5 on 2021-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_gettingstarted_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='allow_to_assignment',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
