# Generated by Django 3.2.5 on 2021-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_week_allow_to_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='allow_to_assignment',
        ),
        migrations.AddField(
            model_name='scorestudent',
            name='allow_to_assignment',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
