# Generated by Django 3.2.7 on 2021-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_scorestudent_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
