# Generated by Django 3.2.7 on 2021-09-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_week_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('great_job', 'Great Job'), ('well_done', 'Well Done'), ('good_try', 'Good Try'), ('need_practice', 'Need More Practice')], max_length=50, null=True)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
        ),
        migrations.CreateModel(
            name='AdminComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week')),
            ],
        ),
    ]
