# Generated by Django 3.2.7 on 2021-09-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_admincomment_feedbackforadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='week',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.week'),
        ),
    ]
