# Generated by Django 3.2.7 on 2021-09-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_admincomment_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.feedbackforadmin'),
        ),
    ]
