# Generated by Django 3.2.7 on 2021-09-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_feedback_feedback_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercomments',
            name='admin_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.admincomment'),
        ),
    ]
