# Generated by Django 3.2.7 on 2021-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_teachercomments_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('great_job', 'Great Job'), ('well_done', 'Well Done'), ('good_try', 'Good Try'), ('need_practice', 'Need More Practice')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackforadmin',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('great_job', 'Great Job'), ('well_done', 'Well Done'), ('good_try', 'Good Try'), ('need_practice', 'Need More Practice')], max_length=50, null=True),
        ),
    ]
