# Generated by Django 3.1.7 on 2021-06-26 11:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'The name of the user can only have letters, digits or the following characters: @/./+/-/_', 'invalid')], verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
                ('confirmed', models.BooleanField(blank=True, default=False, verbose_name='Confirmed?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'New Password',
                'verbose_name_plural': 'New Passwords',
                'ordering': ['-created_at'],
            },
        ),
    ]
